# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  fish-ssh-agent = {
    pname = "fish-ssh-agent";
    version = "master";
    src = fetchFromGitHub {
      owner = "ivakyb";
      repo = "fish_ssh_agent";
      rev = "master";
      fetchSubmodules = false;
      sha256 = "sha256-v9VZY5DCo+iWZawRKVgFvsi33UKwtriSpUzrMhL0S14=";
    };
  };
  fisher = {
    pname = "fisher";
    version = "4.4.4";
    src = fetchFromGitHub {
      owner = "jorgebucaran";
      repo = "fisher";
      rev = "4.4.4";
      fetchSubmodules = false;
      sha256 = "sha256-e8gIaVbuUzTwKtuMPNXBT5STeddYqQegduWBtURLT3M=";
    };
  };
  gitnow = {
    pname = "gitnow";
    version = "2.11.0";
    src = fetchFromGitHub {
      owner = "joseluisq";
      repo = "gitnow";
      rev = "2.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-eImCiEhhbXOkwQqRgpqw481i0Wg4c5nADQlG/O+OH0E=";
    };
  };
}
