[gitnow]
src.github = "joseluisq/gitnow"
fetch.github =  "joseluisq/gitnow"

[fisher]
src.github = "jorgebucaran/fisher"
fetch.github = "jorgebucaran/fisher"

[fish-ssh-agent]
src.manual = "master"
fetch.github = "ivakyb/fish_ssh_agent"
