[gitnow]
src.github = "joseluisq/gitnow"
fetch.github =  "joseluisq/gitnow"

[fisher]
src.github = "jorgebucaran/fisher"
fetch.github = "jorgebucaran/fisher"

[fish-ssh-agent]
src.manual = "master"
fetch.github = "scarvalhojr/fish-ssh-agent"
